### ISSUE TITLE
Page qui sommes-nous ?

### ISSUE THREAD

**Issue by elizlp** [betagouv/open-academie#13]
![capture d ecran 2017-03-28 a 15 30 40](https://cloud.githubusercontent.com/assets/26251074/24407733/0ffc86c2-13cc-11e7-88bf-9ae34afc08f6.png)
![capture d ecran 2017-03-28 a 15 30 51](https://cloud.githubusercontent.com/assets/26251074/24407751/1c087822-13cc-11e7-81e8-6b8dbd1f1f5e.png)
![capture d ecran 2017-03-28 a 15 31 03](https://cloud.githubusercontent.com/assets/26251074/24407760/230c9bb2-13cc-11e7-9563-7d9152c970c4.png)
![capture d ecran 2017-03-28 a 15 31 09](https://cloud.githubusercontent.com/assets/26251074/24407767/25d2ac92-13cc-11e7-87cc-a6ebc60c4b99.png)
![capture d ecran 2017-03-28 a 15 31 17](https://cloud.githubusercontent.com/assets/26251074/24407800/3b86f48a-13cc-11e7-8351-4a818481ea59.png)

**Comment by Flightan** [comment]
Pour reconnaissance: https://codepen.io/dudleystorey/pen/FvJDB

**Comment by MattiSG** [comment]
Juste avant que je me désabonne des notifications : `PS` est un acronyme et s'orthographie donc `PS` et non `Ps` :wink:

👋

**Comment by elizlp** [comment]
merci !

**Comment by Flightan** [comment]
@elizlp pourquoi tu as fermé cette issue ? La page à changé ?

**Comment by elizlp** [comment]
Des petits détails oui, donc j'ai recréé une issue !
