### ISSUE TITLE
Logos colorés

### ISSUE THREAD

**Issue by elizlp** [betagouv/open-academie#2]
![avion](https://cloud.githubusercontent.com/assets/26251074/24363280/aab7ff4c-130f-11e7-943f-3ed3e9450e3a.png)
![chapeau](https://cloud.githubusercontent.com/assets/26251074/24363281/aabacd44-130f-11e7-922f-ec11701e1d82.png)
![check 1](https://cloud.githubusercontent.com/assets/26251074/24363278/aab4f234-130f-11e7-9d3b-bb7a752c0485.png)
![graph](https://cloud.githubusercontent.com/assets/26251074/24363279/aab63d4c-130f-11e7-8364-64216e1aea65.png)
![livre](https://cloud.githubusercontent.com/assets/26251074/24363283/aafc76cc-130f-11e7-9cf3-06cef18b8203.png)

**Comment by Flightan** [comment]
![hat](https://cloud.githubusercontent.com/assets/1475946/24396097/53b3051e-13a2-11e7-81fc-ce327c27953b.png)
![graph](https://cloud.githubusercontent.com/assets/1475946/24396100/53b45608-13a2-11e7-9c03-7b4f87c76a65.png)
![book](https://cloud.githubusercontent.com/assets/1475946/24396098/53b3cdaa-13a2-11e7-9a2f-f22df1365de7.png)
![arrow](https://cloud.githubusercontent.com/assets/1475946/24396099/53b3fd34-13a2-11e7-864a-c41eba7c0c76.png)
