### ISSUE TITLE
Photos témoignages bas page les outils 

### ISSUE THREAD

**Issue by elizlp** [betagouv/open-academie#20]
Est ce que tu pourras mettre les photos dans un cadre rond comme sur le modèle  ?
![capture d ecran 2017-04-10 a 12 01 46](https://cloud.githubusercontent.com/assets/26251074/24857026/11dc6852-1de7-11e7-9c04-67c099087f23.png)

![david_maupin](https://cloud.githubusercontent.com/assets/26251074/24857029/1432dd0c-1de7-11e7-8b3a-d2240ffb9819.jpg)
![corine_hiriart](https://cloud.githubusercontent.com/assets/26251074/24857032/16984000-1de7-11e7-980f-fcfadecd2f7c.jpg)
![myriam_barthel](https://cloud.githubusercontent.com/assets/26251074/24857034/18805d44-1de7-11e7-92a8-a1333f279689.png)
![stephane_franchettit](https://cloud.githubusercontent.com/assets/26251074/24857038/1c25e0cc-1de7-11e7-8f40-ad8db65440e2.png)

**Comment by elizlp** [comment]
Je crois qu'elles ont été recadrées ce qui va peut être rendre le passage au cadre rond plus compliqué. 
On peut retrouver les originales sur l'ancien site Open Académie ou je dois les demander à Pierre ?

**Comment by Flightan** [comment]
On va tenter de mettre un temoignage par page outil, dans les "SalesPoints
![screen shot 2017-07-11 at 14 45 10](https://user-images.githubusercontent.com/1475946/28068891-a21de0e6-6647-11e7-8f83-7a4c029ab3b6.png)
"
