### ISSUE TITLE
Image page Les Outils 

### ISSUE THREAD

**Issue by elizlp** [betagouv/open-academie#3]
https://www.pexels.com/photo/black-round-analog-wall-clock-121734/

**Comment by elizlp** [comment]
Et le titre "Les Outils" en blanc centré 
![capture d ecran 2017-03-27 a 17 10 42](https://cloud.githubusercontent.com/assets/26251074/24363497/5492503a-1310-11e7-87e4-7d29e3bf142a.png)

**Comment by Flightan** [comment]
Comment on accède à cette page ? C'est pas un doublon de la section "Les outils" de la page d'accueil ?

**Comment by elizlp** [comment]
Non c'est la même ! Quand je clique sur l'onglet les outils, cette image s'affiche, et quand je scroll down sur l'écran j'ai la même interface que sur la page d'accueil.
La seule différence c'est que quand j'arrive directement sur la page d'accueil, je n'ai pas l'image.
