### ISSUE TITLE
retours de la team

### ISSUE THREAD

**Issue by MargotDem** [betagouv/open-academie#32]
**Myriam** : magnifique, seul bémol : le bouton "contact" renvoie vers outlook,, ce qui repousse peut être les gens d'aller plus loin 

**Etienne** :
- charte : on a choisi d'appeler les logiciels MachinSCO avec les majuscules comme DossierSCO, MobiliSCO

- autour de la demande de téléchargement d'un logiciel, il serait bon de préciser quelle version est mise à dispo et depuis quand

- nos applis fonctionnent aussi avec Access 2016, en tout cas je les ouvre avec et je ne remarque rien lors d'un test succinct.

- il faut se demander si l'on doit renvoyer les gens vers le Runtime 2010 ; après des tests on pourrait peut-être plutôt faire utiliser une version récente, non ?

- c'est encore très court : pas de captures d'écran, pas de lien vers la discussion entre utilisateurs...

- dans l'argumentaire "gratuit", au lieu de dire réalisé "Élaboré par des agents pour des agents", je propose "par des agents du service public pour eux-mêmes et leurs collègues"

- attention simplification dans GemaSCO, avec la version imminente il ne sera plus nécessaire de se soucier de la police codes-barres (merci Romain)

- e-maintenance n'est pas sous GPL (jusqu'à plus ample informé), et n'est gratuite que pour les EPLE déjà adhérents à l'association !

- "L'appli e-maintenance permet l'entretien et la gestion de tout type de matériel au sein d'un établissement, de l'ampoule grillée au rétroprojecteur en panne." : heu, ce texte est bizarre, on a l'impression que le logiciel va remplacer nos OP. On l'interfacera avec des robots dans un second temps...

- si l'on fait la promo d'e-maintenance, je pense que ça serait bien vu à l'égard d'AJI de promouvoir aussi e-bilan social.

- pour faire une page TrombinoSCO, c'est quand vous voulez, l'appli est prête propre, testée, déployée (Jérôme, tu sais ce qu'il te dit mon "embryon" !?), et on peut faire du client pour la rentrée

- et ça serait pas idiot de préparer en backstage la page DossierSCO parce que c'est mûr et sucré, et que Romain et moi allons vous en faire la release début juillet

- Voilà. D'une manière générale on a quand même pas mal de produits, et ça serait chouette d'en faire une synthèse sous forme de cartographie. Un peu sur le modèle : https://static.latribune.fr/article_body/408580/degoogliser-internet.jpg ?

**Jérôme Boudenant :** Quelques problèmes de
Mise en page sur mon appareil mobile : téléphone portable  (mais ça reste lisible)
Que pensez vous d'y ajouter une section sur les projets/idée en cours de développement à l'état d'embryon? (Gestion des clefs, gestion des trombi, des rapports de verificzrin, duerp...)?
Éventuellement un système pour permettre de s'enregistrer comme étant intéressé par le projet ? Un bon moyen de collecter des adresses de bêta testeurs éventuels, ou de constituer une petite base de données des gens susceptibles d'être informés prioritairement lors des sorties, ou encore de jauger de l'intérêt porté par la communauté sur tel ou tel outil en cours de développement.

**Comment by Flightan** [comment]
On améliorera le mobile, les pages et on ajoutera les produits au fur et à mesure. Je pense qu'il serait bon de faire une formation "Prise en main du site" pour aider à la collaboration on verra lors du prochain OpenLab.

Est-ce que le manque de la partie témoignage est bloquant pour le remplacement du site actuel ?
