### ISSUE TITLE
Supprimer la et les références à Cogefi

### ISSUE THREAD

**Issue by Intendant-zonard** [betagouv/open-academie#52]
Il faut extraire du site la page de l'outil Cogefi.

Etats d'âme de l'auteur principal du logiciel, il est préférable d'ôter ce logiciel de notre catalogue. D'une manière générale, ce projet-là n'a pas tiré parti du coaching à Etalab, il a sa propre vie. Pas la peine d'aller au conflit.

**Comment by Flightan** [comment]
C'est fait
