### ISSUE TITLE
Champs avec un liseré rouge qu'on ne comprend pas

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/open-academie#55]
Sur les pages https://openacademie.beta.gouv.fr/mobilisco et https://openacademie.beta.gouv.fr/gemasco, les champs à remplir pour télécharger les logiciels ont un liseré rouge, qui semble indiquer que ces champs sont en erreur alors qu'on n'a encore rien rentré dedans.

Enlever ce liseré ?

**Comment by Flightan** [comment]
Tu peux m'indiquer sur quelle config ? Je n'arrive pas à reproduire.

**Comment by Flightan** [comment]
Il semble que firefox pense que c'est une bonne idée de rajouter ce liseré sur les champs `required`

**Comment by gregoirenovel** [comment]
Issue liée : https://bugzilla.mozilla.org/show_bug.cgi?id=1399046

Des pistes pour patcher (mais pas vraiment corriger) le problème :
- https://stackoverflow.com/questions/3809146/firefox-4-required-input-form-red-border-outline
- https://stackoverflow.com/questions/5939341/firefox-4-is-there-a-way-to-remove-the-red-border-in-a-required-form-input
