### ISSUE TITLE
Coches tronqués par le fond de la page

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/open-academie#56]
Sur https://openacademie.beta.gouv.fr/mobilisco et https://openacademie.beta.gouv.fr/gemasco, les coches sont "coupés" par le fond de la page, ce qui n'est pas très esthétique.

<img width="1392" alt="screen shot 2017-11-28 at 18 17 47" src="https://user-images.githubusercontent.com/1333173/33333930-98ccb4c4-d468-11e7-8f93-a1fd31e78265.png">

**Comment by Flightan** [comment]
Je suis assez d'accord, c'était pourtant voulu à la base.

**Comment by Morendil** [comment]
On a décidé de ranger ça dans la catégorie "les goûts et les couleurs"
