### ISSUE TITLE
Ajouter une licence libre

### ISSUE THREAD

**Issue by bzg** [betagouv/open-academie#73]
La description du projet indique que le code source est libre, mais je n'ai pas trouvé la licence. Si vous avez besoin d'aide pour choisir, dites-moi - je pense qu'une MIT convient bien.

**Comment by Intendant-zonard** [comment]
Salut,

Dans les outils eux-mêmes, il est indiqué notre intention de nous conformer à la GPL v3, avec le lien vers la FSF. Dans les màj récentes d'ailleurs, j'ajoute le logo.

Il n'y a pas à proprement parler de code-source distinct de l'application elle-même, et à l'intérieur des application on trouve facilement le lien vers le journal de développement et débogage en ligne (un simple framacalc en fait). 

Tout ça est du travail d'amateurs, mais je m'efforce de convenir à l'esprit de la licence, en tout cas pour ce que j'ai compris. Ce qui serait bien, ça serait d'intégrer la référence la GPL dans le site lui-même aussi, je présume.

**Comment by bzg** [comment]
Merci pour ta réactivité ! L'idée est simplement d'ajouter un fichier LICENSE.txt qui va bien avec la licence qui va bien à la racine des dépôts de code source des applications développées.  Se conformer à l'esprit d'une licence ne suffit pas, il faut écrire noir sur blanc quelle licence est utilisée.

Je ne suis pas sûr d'avoir compris quels sont les dépôts pertinents du coup (j'ai trouvé celui-ci en partant des informations publiées sur [cette page](https://beta.gouv.fr/startups/open-academie.html).

Si je peux aider plus, n'hésite pas !

**Comment by bzg** [comment]
Bonjour ! Est-ce que cela t'avance si je fais moi-même la PR pour ajouter la licence ?

**Comment by Intendant-zonard** [comment]
Oui, ça serait super, merci Bastien !

----- Mail original -----
> De: "Bastien" <notifications@github.com>
> À: "betagouv/open-academie" <open-academie@noreply.github.com>
> Cc: "Intendant-zonard" <etienne@intendancezone.net>, "Comment" <comment@noreply.github.com>
> Envoyé: Jeudi 26 Septembre 2019 15:12:14
> Objet: Re: [betagouv/open-academie] Ajouter une licence libre (#73)
> 
> 
> 
> Bonjour ! Est-ce que cela t'avance si je fais moi-même la PR pour
> ajouter la licence ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or mute the thread
> .

-- 
Étienne ANDRÉ
http://www.intendancezone.net
Tél direct 01 48 99 99 22

**Comment by bzg** [comment]
Hello, j'ai donc fait une PR.  De ce que j'ai compris en lisant le site, ce sont certains logiciels à part (comme Mobilisco) qui seraient "dans l'esprit de" la licence GPL.  Du coup je pense que la MIT est plus appropriée pour ce dépôt sur le site du projet, et je peux faire des PR pour ajouter la GPL sur les autres dépôts si tu m'aides à les trouver :)

En espérant que cela aide.  Bonne soirée !

**Comment by bzg** [comment]
Hello, est-ce qu'il y a un souci pour merger la PR que j'ai faite ? A disposition pour éclaircir ou aider si besoin. Bonne journée !

**Comment by Intendant-zonard** [comment]
Salut Bastien,

Pardon je n'ai pas l'habitude de me considérer comme directeur de publication sur cette vitrine, historiquement tout revenait à Florian.

Bref, ajouter la licence très bien, la MIT pourquoi pas (si la GPL pose un problème, ce que je peux imaginer étant donné la fragilité de ce qu'on fait il peut y avoir une incompatibilité ça ne m'étonnerait pas)

Si c'est utile maintenant que j'en aile droit, je cliquerai sur merge.

Autre sujet : j'ai besoin d'une petite maintenance sur la liste de diffusion contact@openacademie.beta.gouv.fr

* <gregory.grandjean@ac-nancy-metz.fr> ne marche plus, à ôter
* remplacer par "Gregory GRANDJEAN" <agent.comptable@lycee-schuman.eu>



----- Mail original -----
> De: "Bastien" <notifications@github.com>
> À: "betagouv/open-academie" <open-academie@noreply.github.com>
> Cc: "Intendant-zonard" <etienne@intendancezone.net>, "Comment" <comment@noreply.github.com>
> Envoyé: Lundi 11 Novembre 2019 12:17:50
> Objet: Re: [betagouv/open-academie] Ajouter une licence libre (#73)
> 
> 
> 
> Hello, est-ce qu'il y a un souci pour merger la PR que j'ai faite ? A
> disposition pour éclaircir ou aider si besoin. Bonne journée !
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or unsubscribe .

-- 
Étienne ANDRÉ
http://www.intendancezone.net
Tél direct 01 48 99 99 22

**Comment by Intendant-zonard** [comment]
Zut, j'ai laissé partir le précédent message avant d'avoir terminé.

----- Mail original -----
> De: "Étienne ANDRÉ" <etienne@intendancezone.net>
 
> Autre sujet : j'ai besoin d'une petite maintenance sur la liste de
> diffusion contact@openacademie.beta.gouv.fr
> 
> * <gregory.grandjean@ac-nancy-metz.fr> ne marche plus, à ôter
> * remplacer par "Gregory GRANDJEAN"
> <agent.comptable@lycee-schuman.eu>

* <aude.saint-gratien@ac-nancy-metz.fr> est HS, à ôter
* remplacer par <saintgratien@lilo.org>

* ajouter claudine.gevaudant@aji-france.com

Est-ce que c'est dans tes cordes ? Sinon je renvoie à Laurent Bossavit, avec un peu de chance...

Merci d'avance,

-- 
Étienne ANDRÉ
http://www.intendancezone.net
Tél direct 01 48 99 99 22

**Comment by bzg** [comment]
> Si c'est utile maintenant que j'en aile droit, je cliquerai sur merge.

Oui, c'est utile et tu en as le droit ! Go :)

Pour le reste, je n'ai pas la main dessus, je laisse les autres te répondre.

**Comment by Intendant-zonard** [comment]
OK je renvoie ma question, pas en deux épisodes, à Laurent, en espérant qu'il ait la main là-dessus. Sinon il faudra déranger Florian, mais si j'ai bien compris c'est lui le grand chef désormais, j'imagine que ça serait pas plus mal de le lui épargner.

Bye,

----- Mail original -----
> De: "Bastien" <notifications@github.com>
> À: "betagouv/open-academie" <open-academie@noreply.github.com>
> Cc: "Intendant-zonard" <etienne@intendancezone.net>, "Comment" <comment@noreply.github.com>
> Envoyé: Mercredi 13 Novembre 2019 17:41:44
> Objet: Re: [betagouv/open-academie] Ajouter une licence libre (#73)
> 
> 
> 
> 
> 
> Si c'est utile maintenant que j'en aile droit, je cliquerai sur
> merge.
> 
> Oui, c'est utile et tu en as le droit ! Go :)
> 
> Pour le reste, je n'ai pas la main dessus, je laisse les autres te
> répondre.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or unsubscribe .

-- 
Étienne ANDRÉ
http://www.intendancezone.net
Tél direct 01 48 99 99 22
